using System;

namespace Lawn
{
	public enum GameObjectType
	{
		OBJECT_TYPE_NONE,
		OBJECT_TYPE_PLANT,
		OBJECT_TYPE_PROJECTILE,
		OBJECT_TYPE_COIN,
		OBJECT_TYPE_SEEDPACKET,
		OBJECT_TYPE_SHOVEL,
		OBJECT_TYPE_WATERING_CAN,
		OBJECT_TYPE_FERTILIZER,
		OBJECT_TYPE_BUG_SPRAY,
		OBJECT_TYPE_PHONOGRAPH,
		OBJECT_TYPE_CHOCOLATE,
		OBJECT_TYPE_GLOVE,
		OBJECT_TYPE_MONEY_SIGN,
		OBJECT_TYPE_WHEELBARROW,
		OBJECT_TYPE_TREE_FOOD,
		OBJECT_TYPE_NEXT_GARDEN,
		OBJECT_TYPE_MENU_BUTTON,
		OBJECT_TYPE_STORE_BUTTON,
		OBJECT_TYPE_SLOT_MACHINE_HANDLE,
		OBJECT_TYPE_SCARY_POT,
		OBJECT_TYPE_STINKY,
		OBJECT_TYPE_TREE_OF_WISDOM
	}
}
