using System;

namespace Sexy
{
	public enum InterfaceWidgets
	{
		UI_WIDGET_LOAD,
		UI_WIDGET_DEMO,
		UI_WIDGET_BACK,
		UI_WIDGET_MENU,
		UI_WIDGET_BORD,
		UI_WIDGET_FXOV,
		UI_WIDGET_INFO,
		UI_WIDGET_SCOR,
		UI_WIDGET_LEAD,
		UI_WIDGET_NAME,
		UI_WIDGET_OVER,
		UI_WIDGET_BLOV,
		UI_WIDGET_HELP,
		UI_WIDGET_MORE,
		UI_WIDGET_CONN,
		UI_WIDGET_COUNT
	}
}
