using System;

namespace Lawn
{
	public enum CoinType
	{
		COIN_NONE,
		COIN_SILVER,
		COIN_GOLD,
		COIN_DIAMOND,
		COIN_SUN,
		COIN_SMALLSUN,
		COIN_LARGESUN,
		COIN_FINAL_SEED_PACKET,
		COIN_TROPHY,
		COIN_SHOVEL,
		COIN_ALMANAC,
		COIN_CARKEYS,
		COIN_WATERING_CAN,
		COIN_TACO,
		COIN_NOTE,
		COIN_USABLE_SEED_PACKET,
		COIN_PRESENT_PLANT,
		COIN_AWARD_MONEY_BAG,
		COIN_AWARD_PRESENT,
		COIN_AWARD_BAG_DIAMOND,
		COIN_CHOCOLATE,
		COIN_AWARD_CHOCOLATE,
		COIN_PRESENT_MINIGAMES,
		COIN_PRESENT_PUZZLE_MODE,
		COIN_BACON
	}
}
