using System;

namespace Lawn
{
	public enum CoinMotion
	{
		COIN_MOTION_FROM_SKY,
		COIN_MOTION_FROM_SKY_SLOW,
		COIN_MOTION_FROM_PLANT,
		COIN_MOTION_COIN,
		COIN_MOTION_LAWNMOWER_COIN,
		COIN_MOTION_FROM_PRESENT,
		COIN_MOTION_FROM_BOSS
	}
}
