using System;

namespace Lawn
{
    public enum StoreItem
    {
        STORE_ITEM_PLANT_GATLINGPEA,
        STORE_ITEM_PLANT_TWINSUNFLOWER,
        STORE_ITEM_PLANT_GLOOMSHROOM,
        STORE_ITEM_PLANT_CATTAIL,
        STORE_ITEM_PLANT_WINTERMELON,
        STORE_ITEM_PLANT_GOLD_MAGNET,
        STORE_ITEM_PLANT_SPIKEROCK,
        STORE_ITEM_PLANT_COBCANNON,
        STORE_ITEM_PLANT_IMITATER,
        STORE_ITEM_BONUS_LAWN_MOWER,
        STORE_ITEM_POTTED_MARIGOLD_1,
        STORE_ITEM_POTTED_MARIGOLD_2,
        STORE_ITEM_POTTED_MARIGOLD_3,
        STORE_ITEM_GOLD_WATERINGCAN,
        STORE_ITEM_FERTILIZER,
        STORE_ITEM_BUG_SPRAY,
        STORE_ITEM_PHONOGRAPH,
        STORE_ITEM_GARDENING_GLOVE,
        STORE_ITEM_MUSHROOM_GARDEN,
        STORE_ITEM_WHEEL_BARROW,
        STORE_ITEM_STINKY_THE_SNAIL,
        STORE_ITEM_PACKET_UPGRADE,
        STORE_ITEM_POOL_CLEANER,
        STORE_ITEM_ROOF_CLEANER,
        STORE_ITEM_RAKE,
        STORE_ITEM_AQUARIUM_GARDEN,
        STORE_ITEM_CHOCOLATE,
        STORE_ITEM_TREE_OF_WISDOM,
        STORE_ITEM_TREE_FOOD,
        STORE_ITEM_FIRSTAID,
        STORE_ITEM_INVALID = -1
    }
}
