using System;

namespace Sexy
{
	public enum MessageBoxResults
	{
		MSGBOX_RESULT_OK = 1,
		MSGBOX_RESULT_CANCEL,
		MSGBOX_RESULT_ABORT,
		MSGBOX_RESULT_RETRY,
		MSGBOX_RESULT_IGNORE,
		MSGBOX_RESULT_YES,
		MSGBOX_RESULT_NO,
		MSGBOX_RESULT_TRYAGAIN = 10,
		MSGBOX_RESULT_CONTINUE
	}
}
