using System;

namespace Sexy.TodLib
{
	public enum ReanimLoopType
	{
		REANIM_LOOP,
		REANIM_LOOP_FULL_LAST_FRAME,
		REANIM_PLAY_ONCE,
		REANIM_PLAY_ONCE_AND_HOLD,
		REANIM_PLAY_ONCE_FULL_LAST_FRAME,
		REANIM_PLAY_ONCE_FULL_LAST_FRAME_AND_HOLD
	}
}
