using System;

namespace Lawn
{
	public/*internal*/ enum BackgroundType
	{
		BACKGROUND_1_DAY,
		BACKGROUND_2_NIGHT,
		BACKGROUND_3_POOL,
		BACKGROUND_4_FOG,
		BACKGROUND_5_ROOF,
		BACKGROUND_6_BOSS,
		BACKGROUND_MUSHROOM_GARDEN,
		BACKGROUND_GREENHOUSE,
		BACKGROUND_ZOMBIQUARIUM,
		BACKGROUND_TREE_OF_WISDOM
	}
}
