using System;

namespace Lawn
{
	public enum DamageFlags
	{
		DAMAGE_BYPASSES_SHIELD,
		DAMAGE_HITS_SHIELD_AND_BODY,
		DAMAGE_FREEZE,
		DAMAGE_DOESNT_CAUSE_FLASH,
		DAMAGE_DOESNT_LEAVE_BODY,
		DAMAGE_SPIKE
	}
}
