using System;

namespace Lawn
{
	internal enum TutorialState
	{
		TUTORIAL_OFF,
		TUTORIAL_LEVEL_1_PICK_UP_PEASHOOTER,
		TUTORIAL_LEVEL_1_PLANT_PEASHOOTER,
		TUTORIAL_LEVEL_1_REFRESH_PEASHOOTER,
		TUTORIAL_LEVEL_1_COMPLETED,
		TUTORIAL_LEVEL_2_PICK_UP_SUNFLOWER,
		TUTORIAL_LEVEL_2_PLANT_SUNFLOWER,
		TUTORIAL_LEVEL_2_REFRESH_SUNFLOWER,
		TUTORIAL_LEVEL_2_COMPLETED,
		TUTORIAL_MORESUN_PICK_UP_SUNFLOWER,
		TUTORIAL_MORESUN_PLANT_SUNFLOWER,
		TUTORIAL_MORESUN_REFRESH_SUNFLOWER,
		TUTORIAL_MORESUN_COMPLETED,
		TUTORIAL_SLOT_MACHINE_PULL,
		TUTORIAL_SLOT_MACHINE_COMPLETED,
		TUTORIAL_SHOVEL_PICKUP,
		TUTORIAL_SHOVEL_DIG,
		TUTORIAL_SHOVEL_KEEP_DIGGING,
		TUTORIAL_SHOVEL_COMPLETED,
		TUTORIAL_ZOMBIQUARIUM_BUY_SNORKEL,
		TUTORIAL_ZOMBIQUARIUM_BOUGHT_SNORKEL,
		TUTORIAL_ZOMBIQUARIUM_CLICK_TROPHY,
		TUTORIAL_ZEN_GARDEN_PICKUP_WATER,
		TUTORIAL_ZEN_GARDEN_WATER_PLANT,
		TUTORIAL_ZEN_GARDEN_KEEP_WATERING,
		TUTORIAL_ZEN_GARDEN_VISIT_STORE,
		TUTORIAL_ZEN_GARDEN_FERTILIZE_PLANTS,
		TUTORIAL_ZEN_GARDEN_COMPLETED,
		TUTORIAL_WHACK_A_ZOMBIE_BEFORE_PICK_SEED,
		TUTORIAL_WHACK_A_ZOMBIE_PICK_SEED,
		TUTORIAL_WHACK_A_ZOMBIE_COMPLETED
	}
}
