using System;

namespace Lawn
{
	public enum GraveStoneLayers
	{
		GRAVESTONE_LAYER_BRAIN,
		GRAVESTONE_LAYER_SQUIRREL,
		GRAVESTONE_LAYER_DOOR2,
		GRAVESTONE_LAYER_STONES,
		GRAVESTONE_LAYER_DOOR1,
		GRAVESTONE_LAYER_DAISIES,
		GRAVESTONE_LAYER_BOSS_FIREBALL,
		GRAVESTONE_LAYER_BUNGEE,
		GRAVESTONE_LAYER_SQUISHED_PLANT,
		GRAVESTONE_LAYER_RAKE
	}
}
