using System;

namespace Lawn
{
	public enum RenderObjectType
	{
		RENDER_ITEM_COIN = 1,
		RENDER_ITEM_PROJECTILE,
		RENDER_ITEM_ZOMBIE,
		RENDER_ITEM_ZOMBIE_SHADOW,
		RENDER_ITEM_ZOMBIE_BUNGEE_TARGET,
		RENDER_ITEM_PLANT,
		RENDER_ITEM_PLANT_OVERLAY,
		RENDER_ITEM_PLANT_MAGNET_ITEMS,
		RENDER_ITEM_CURSOR_PREVIEW,
		RENDER_ITEM_PARTICLE,
		RENDER_ITEM_REANIMATION,
		RENDER_ITEM_ICE,
		RENDER_ITEM_TOP_UI,
		RENDER_ITEM_FOG,
		RENDER_ITEM_STORM,
		RENDER_ITEM_BOTTOM_UI,
		RENDER_ITEM_BACKDROP,
		RENDER_ITEM_DOOR_MASK,
		RENDER_ITEM_COIN_BANK,
		RENDER_ITEM_PROJECTILE_SHADOW,
		RENDER_ITEM_MOWER,
		RENDER_ITEM_SCREEN_FADE,
		RENDER_ITEM_BOSS_PART,
		RENDER_ITEM_GRID_ITEM,
		RENDER_ITEM_GRID_ITEM_OVERLAY
	}
}
