using System;

namespace Lawn
{
	public enum GridItemState
	{
		GRIDITEM_STATE_NORMAL,
		GRIDITEM_STATE_GRAVESTONE_SPECIAL,
		GRIDITEM_STATE_PORTAL_CLOSED,
		GRIDITEM_STATE_SCARY_POT_QUESTION,
		GRIDITEM_STATE_SCARY_POT_LEAF,
		GRIDITEM_STATE_SCARY_POT_ZOMBIE,
		GRIDITEM_STATE_SQUIRREL_WAITING,
		GRIDITEM_STATE_SQUIRREL_PEEKING,
		GRIDITEM_STATE_SQUIRREL_RUNNING_UP,
		GRIDITEM_STATE_SQUIRREL_RUNNING_DOWN,
		GRIDITEM_STATE_SQUIRREL_RUNNING_LEFT,
		GRIDITEM_STATE_SQUIRREL_RUNNING_RIGHT,
		GRIDITEM_STATE_SQUIRREL_CAUGHT,
		GRIDITEM_STATE_SQUIRREL_ZOMBIE,
		GRIDITEM_STATE_ZEN_TOOL_WATERING_CAN,
		GRIDITEM_STATE_ZEN_TOOL_FERTILIZER,
		GRIDITEM_STATE_ZEN_TOOL_BUG_SPRAY,
		GRIDITEM_STATE_ZEN_TOOL_PHONOGRAPH,
		GRIDITEM_STATE_ZEN_TOOL_GOLD_WATERING_CAN,
		GRIDITEM_STINKY_WALKING_LEFT,
		GRIDITEM_STINKY_TURNING_LEFT,
		GRIDITEM_STINKY_WALKING_RIGHT,
		GRIDITEM_STINKY_TURNING_RIGHT,
		GRIDITEM_STINKY_SLEEPING,
		GRIDITEM_STINKY_FALLING_ASLEEP,
		GRIDITEM_STINKY_WAKING_UP,
		GRIDITEM_STATE_RAKE_ATTRACTING,
		GRIDITEM_STATE_RAKE_WAITING,
		GRIDITEM_STATE_RAKE_TRIGGERED,
		GRIDITEM_STATE_BRAIN_SQUISHED
	}
}
