using System;

namespace Lawn
{
	public enum ChallengeState
	{
		STATECHALLENGE_NORMAL,
		STATECHALLENGE_BEGHOULED_MOVING,
		STATECHALLENGE_BEGHOULED_FALLING,
		STATECHALLENGE_BEGHOULED_NO_MATCHES,
		STATECHALLENGE_SLOT_MACHINE_ROLLING,
		STATECHALLENGE_STORM_FLASH_1,
		STATECHALLENGE_STORM_FLASH_2,
		STATECHALLENGE_STORM_FLASH_3,
		STATECHALLENGE_ZEN_FADING,
		STATECHALLENGE_SCARY_POTTER_MALLETING,
		STATECHALLENGE_LAST_STAND_ONSLAUGHT,
		STATECHALLENGE_TREE_JUST_GREW,
		STATECHALLENGE_TREE_GIVE_WISDOM,
		STATECHALLENGE_TREE_WAITING_TO_BABBLE,
		STATECHALLENGE_TREE_BABBLING
	}
}
