using System;

namespace Lawn
{
	public enum ZombieType
	{
		ZOMBIE_INVALID = -1,
		ZOMBIE_NORMAL,
		ZOMBIE_FLAG,
		ZOMBIE_TRAFFIC_CONE,
		ZOMBIE_POLEVAULTER,
		ZOMBIE_PAIL,
		ZOMBIE_NEWSPAPER,
		ZOMBIE_DOOR,
		ZOMBIE_FOOTBALL,
		ZOMBIE_DANCER,
		ZOMBIE_BACKUP_DANCER,
		ZOMBIE_DUCKY_TUBE,
		ZOMBIE_SNORKEL,
		ZOMBIE_ZAMBONI,
		ZOMBIE_BOBSLED,
		ZOMBIE_DOLPHIN_RIDER,
		ZOMBIE_JACK_IN_THE_BOX,
		ZOMBIE_BALLOON,
		ZOMBIE_DIGGER,
		ZOMBIE_POGO,
		ZOMBIE_YETI,
		ZOMBIE_BUNGEE,
		ZOMBIE_LADDER,
		ZOMBIE_CATAPULT,
		ZOMBIE_GARGANTUAR,
		ZOMBIE_IMP,
		ZOMBIE_BOSS,
		ZOMBIE_PEA_HEAD,
		ZOMBIE_WALLNUT_HEAD,
		ZOMBIE_JALAPENO_HEAD,
		ZOMBIE_GATLING_HEAD,
		ZOMBIE_SQUASH_HEAD,
		ZOMBIE_TALLNUT_HEAD,
		ZOMBIE_REDEYE_GARGANTUAR,
		NUM_ZOMBIE_TYPES,
		ZOMBIE_CACHED_POLEVAULTER_WITH_POLE,
		NUM_CACHED_ZOMBIE_TYPES
	}
}
