using System;

namespace Lawn
{
	public enum CrazyDaveState
	{
		CRAZY_DAVE_OFF,
		CRAZY_DAVE_ENTERING,
		CRAZY_DAVE_LEAVING,
		CRAZY_DAVE_IDLING,
		CRAZY_DAVE_TALKING,
		CRAZY_DAVE_HANDING_TALKING,
		CRAZY_DAVE_HANDING_IDLING
	}
}
