using System;

namespace Sexy.TodLib
{
	public enum FoleyFlags
	{
		FOLEYFLAGS_LOOP,
		FOLEYFLAGS_ONE_AT_A_TIME,
		FOLEYFLAGS_MUTE_ON_PAUSE,
		FOLEYFLAGS_USES_MUSIC_VOLUME,
		FOLEYFLAGS_DONT_REPEAT
	}
}
