using System;

namespace Sexy.Drivers
{
	public enum GamepadButton
	{
		GAMEPAD_BUTTON_UP,
		GAMEPAD_BUTTON_DOWN,
		GAMEPAD_BUTTON_LEFT,
		GAMEPAD_BUTTON_RIGHT,
		GAMEPAD_BUTTON_BACK,
		GAMEPAD_BUTTON_START,
		GAMEPAD_BUTTON_A,
		GAMEPAD_BUTTON_B,
		GAMEPAD_BUTTON_X,
		GAMEPAD_BUTTON_Y,
		GAMEPAD_BUTTON_LB,
		GAMEPAD_BUTTON_RB,
		GAMEPAD_BUTTON_LTRIGGER,
		GAMEPAD_BUTTON_RTRIGGER,
		GAMEPAD_BUTTON_LSTICK,
		GAMEPAD_BUTTON_RSTICK,
		GAMEPAD_BUTTON_DPAD_UP,
		GAMEPAD_BUTTON_DPAD_DOWN,
		GAMEPAD_BUTTON_DPAD_LEFT,
		GAMEPAD_BUTTON_DPAD_RIGHT,
		_GAMEPAD_BUTTON_NUM,
		GAMEPAD_BUTTON_PS_CROSS = 6,
		GAMEPAD_BUTTON_PS_SQUARE = 8,
		GAMEPAD_BUTTON_PS_CIRCLE = 7,
		GAMEPAD_BUTTON_PS_TRIANGLE = 9,
		GAMEPAD_BUTTON_PS_L1,
		GAMEPAD_BUTTON_PS_L2 = 12,
		GAMEPAD_BUTTON_PS_L3 = 14,
		GAMEPAD_BUTTON_PS_R1 = 11,
		GAMEPAD_BUTTON_PS_R2 = 13,
		GAMEPAD_BUTTON_PS_R3 = 15,
		GAMEPAD_BUTTON_PS_START = 5,
		GAMEPAD_BUTTON_PS_SELECT = 4
	}
}
