using System;

namespace Sexy.Drivers
{
	public enum HttpStatusCodes
	{
		HTTP_CONTINUE = 100,
		HTTP_SWITCH_PROTOCOLS,
		HTTP_OK = 200,
		HTTP_CREATED,
		HTTP_ACCEPTED,
		HTTP_PARTIAL,
		HTTP_NO_CONTENT,
		HTTP_RESET_CONTENT,
		HTTP_PARTIAL_CONTENT,
		HTTP_WEBDAV_MULTI_STATUS,
		HTTP_AMBIGUOUS = 300,
		HTTP_MOVED,
		HTTP_REDIRECT,
		HTTP_REDIRECT_METHOD,
		HTTP_NOT_MODIFIED,
		HTTP_USE_PROXY,
		HTTP_REDIRECT_KEEP_VERB = 307,
		HTTP_BAD_REQUEST = 400,
		HTTP_DENIED,
		HTTP_PAYMENT_REQ,
		HTTP_FORBIDDEN,
		HTTP_NOT_FOUND,
		HTTP_BAD_METHOD,
		HTTP_NONE_ACCEPTABLE,
		HTTP_PROXY_AUTH_REQ,
		HTTP_REQUEST_TIMEOUT,
		HTTP_CONFLICT,
		HTTP_GONE,
		HTTP_LENGTH_REQUIRED,
		HTTP_PRECOND_FAILED,
		HTTP_REQUEST_TOO_LARGE,
		HTTP_URI_TOO_LONG,
		HTTP_UNSUPPORTED_MEDIA,
		HTTP_RETRY_WITH = 449,
		HTTP_SERVER_ERROR = 500,
		HTTP_NOT_SUPPORTED,
		HTTP_BAD_GATEWAY,
		HTTP_SERVICE_UNAVAIL,
		HTTP_GATEWAY_TIMEOUT,
		HTTP_VERSION_NOT_SUP
	}
}
