using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DBLENDOP
	{
		SEXY3DBLENDOP_ADD = 1,
		SEXY3DBLENDOP_SUBTRACT,
		SEXY3DBLENDOP_REVSUBTRACT,
		SEXY3DBLENDOP_MIN,
		SEXY3DBLENDOP_MAX,
		SEXY3DBLENDOP_FORCE_DWORD = 2147483647
	}
}
