using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DBLENDMODE
	{
		SEXY3DBLEND_ZERO = 1,
		SEXY3DBLEND_ONE,
		SEXY3DBLEND_SRCCOLOR,
		SEXY3DBLEND_INVSRCCOLOR,
		SEXY3DBLEND_SRCALPHA,
		SEXY3DBLEND_INVSRCALPHA,
		SEXY3DBLEND_DESTALPHA,
		SEXY3DBLEND_INVDESTALPHA,
		SEXY3DBLEND_DESTCOLOR,
		SEXY3DBLEND_INVDESTCOLOR,
		SEXY3DBLEND_SRCALPHASAT,
		SEXY3DBLEND_BOTHSRCALPHA,
		SEXY3DBLEND_BOTHINVSRCALPHA,
		SEXY3DBLEND_BLENDFACTOR,
		SEXY3DBLEND_INVBLENDFACTOR,
		SEXY3DBLEND_FORCE_DWORD = 2147483647
	}
}
