using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DTEXTUREFILTERTYPE
	{
		SEXY3DTEXF_NONE,
		SEXY3DTEXF_POINT,
		SEXY3DTEXF_LINEAR,
		SEXY3DTEXF_ANISOTROPIC,
		SEXY3DTEXF_PYRAMIDALQUAD = 6,
		SEXY3DTEXF_GAUSSIANQUAD,
		SEXY3DTEXF_FORCE_DWORD = 2147483647
	}
}
