using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DTEXTUREADDRESS
	{
		SEXY3DTADDRESS_WRAP = 1,
		SEXY3DTADDRESS_MIRROR,
		SEXY3DTADDRESS_CLAMP,
		SEXY3DTADDRESS_BORDER,
		SEXY3DTADDRESS_MIRRORONCE,
		SEXY3DTADDRESS_FORCE_DWORD = 2147483647
	}
}
