using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DCMPFUNC
	{
		SEXY3DCMP_NEVER = 1,
		SEXY3DCMP_LESS,
		SEXY3DCMP_EQUAL,
		SEXY3DCMP_LESSEQUAL,
		SEXY3DCMP_GREATER,
		SEXY3DCMP_NOTEQUAL,
		SEXY3DCMP_GREATEREQUAL,
		SEXY3DCMP_ALWAYS,
		SEXY3DCMP_FORCE_DWORD = 2147483647
	}
}
