using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DPOOL
	{
		SEXY3DPOOL_DEFAULT,
		SEXY3DPOOL_MANAGED,
		SEXY3DPOOL_SYSTEMMEM,
		SEXY3DPOOL_SCRATCH,
		SEXY3DPOOL_FORCE_DWORD = 2147483647
	}
}
