using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DPRIMITIVETYPE
	{
		SEXY3DPT_POINTLIST = 1,
		SEXY3DPT_LINELIST,
		SEXY3DPT_LINESTRIP,
		SEXY3DPT_TRIANGLELIST,
		SEXY3DPT_TRIANGLESTRIP,
		SEXY3DPT_TRIANGLEFAN,
		SEXY3DPT_FORCE_DWORD = 2147483647
	}
}
