using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DCUBEMAP_FACES
	{
		SEXY3DCUBEMAP_FACE_POSITIVE_X,
		SEXY3DCUBEMAP_FACE_NEGATIVE_X,
		SEXY3DCUBEMAP_FACE_POSITIVE_Y,
		SEXY3DCUBEMAP_FACE_NEGATIVE_Y,
		SEXY3DCUBEMAP_FACE_POSITIVE_Z,
		SEXY3DCUBEMAP_FACE_NEGATIVE_Z,
		SEXY3DCUBEMAP_FACE_FORCE_DWORD = 2147483647
	}
}
