using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DTRANSFORMSTATETYPE
	{
		SEXY3DTS_VIEW = 2,
		SEXY3DTS_PROJECTION,
		SEXY3DTS_TEXTURE0 = 16,
		SEXY3DTS_TEXTURE1,
		SEXY3DTS_TEXTURE2,
		SEXY3DTS_TEXTURE3,
		SEXY3DTS_TEXTURE4,
		SEXY3DTS_TEXTURE5,
		SEXY3DTS_TEXTURE6,
		SEXY3DTS_TEXTURE7,
		SEXY3DTS_FORCE_DWORD = 2147483647
	}
}
