using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DTEXTURETRANSFORMFLAGS
	{
		SEXY3DTTFF_DISABLE,
		SEXY3DTTFF_COUNT1,
		SEXY3DTTFF_COUNT2,
		SEXY3DTTFF_COUNT3,
		SEXY3DTTFF_COUNT4,
		SEXY3DTTFF_PROJECTED = 256,
		SEXY3DTTFF_FORCE_DWORD = 2147483647
	}
}
