using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DSTENCILOP
	{
		SEXY3DSTENCILOP_KEEP = 1,
		SEXY3DSTENCILOP_ZERO,
		SEXY3DSTENCILOP_REPLACE,
		SEXY3DSTENCILOP_INCRSAT,
		SEXY3DSTENCILOP_DECRSAT,
		SEXY3DSTENCILOP_INVERT,
		SEXY3DSTENCILOP_INCR,
		SEXY3DSTENCILOP_DECR,
		SEXY3DSTENCILOP_FORCE_DWORD = 2147483647
	}
}
