using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DTEXTURESTAGESTATETYPE
	{
		SEXY3DTSS_COLOROP = 1,
		SEXY3DTSS_COLORARG1,
		SEXY3DTSS_COLORARG2,
		SEXY3DTSS_ALPHAOP,
		SEXY3DTSS_ALPHAARG1,
		SEXY3DTSS_ALPHAARG2,
		SEXY3DTSS_BUMPENVMAT00,
		SEXY3DTSS_BUMPENVMAT01,
		SEXY3DTSS_BUMPENVMAT10,
		SEXY3DTSS_BUMPENVMAT11,
		SEXY3DTSS_TEXCOORDINDEX,
		SEXY3DTSS_BUMPENVLSCALE = 22,
		SEXY3DTSS_BUMPENVLOFFSET,
		SEXY3DTSS_TEXTURETRANSFORMFLAGS,
		SEXY3DTSS_COLORARG0 = 26,
		SEXY3DTSS_ALPHAARG0,
		SEXY3DTSS_RESULTARG,
		SEXY3DTSS_CONSTANT = 32,
		SEXY3DTSS_FORCE_DWORD = 2147483647
	}
}
