using System;

namespace Sexy.GraphicsLib
{
	public enum SEXY3DSAMPLERSTATETYPE
	{
		SEXY3DSAMP_ADDRESSU = 1,
		SEXY3DSAMP_ADDRESSV,
		SEXY3DSAMP_ADDRESSW,
		SEXY3DSAMP_BORDERCOLOR,
		SEXY3DSAMP_MAGFILTER,
		SEXY3DSAMP_MINFILTER,
		SEXY3DSAMP_MIPFILTER,
		SEXY3DSAMP_MIPMAPLODBIAS,
		SEXY3DSAMP_MAXMIPLEVEL,
		SEXY3DSAMP_MAXANISOTROPY,
		SEXY3DSAMP_SRGBTEXTURE,
		SEXY3DSAMP_ELEMENTINDEX,
		SEXY3DSAMP_DMAPOFFSET,
		SEXY3DSAMP_FORCE_DWORD = 2147483647
	}
}
