using System;

namespace Lawn
{
	public enum MagnetItemType
	{
		MAGNET_ITEM_NONE,
		MAGNET_ITEM_PAIL_1,
		MAGNET_ITEM_PAIL_2,
		MAGNET_ITEM_PAIL_3,
		MAGNET_ITEM_FOOTBALL_HELMET_1,
		MAGNET_ITEM_FOOTBALL_HELMET_2,
		MAGNET_ITEM_FOOTBALL_HELMET_3,
		MAGNET_ITEM_DOOR_1,
		MAGNET_ITEM_DOOR_2,
		MAGNET_ITEM_DOOR_3,
		MAGNET_ITEM_POGO_1,
		MAGNET_ITEM_POGO_2,
		MAGNET_ITEM_POGO_3,
		MAGNET_ITEM_JACK_IN_THE_BOX,
		MAGNET_ITEM_LADDER_1,
		MAGNET_ITEM_LADDER_2,
		MAGNET_ITEM_LADDER_3,
		MAGNET_ITEM_LADDER_PLACED,
		MAGNET_ITEM_SILVER_COIN,
		MAGNET_ITEM_GOLD_COIN,
		MAGNET_ITEM_DIAMOND,
		MAGNET_ITEM_PICK_AXE
	}
}
