using System;

namespace Lawn
{
	public enum PLANT_LAYER
	{
		PLANT_LAYER_BELOW = -1,
		PLANT_LAYER_MAIN,
		PLANT_LAYER_REANIM,
		PLANT_LAYER_REANIM_HEAD,
		PLANT_LAYER_REANIM_BLINK,
		PLANT_LAYER_ON_TOP,
		NUM_PLANT_LAYERS
	}
}
