using System;

namespace Lawn
{
	public/*internal*/ enum PlantPriority
	{
		TOPPLANT_EATING_ORDER,
		TOPPLANT_DIGGING_ORDER,
		TOPPLANT_BUNGEE_ORDER,
		TOPPLANT_CATAPULT_ORDER,
		TOPPLANT_ZEN_TOOL_ORDER,
		TOPPLANT_ANY,
		TOPPLANT_ONLY_NORMAL_POSITION,
		TOPPLANT_ONLY_FLYING,
		TOPPLANT_ONLY_PUMPKIN,
		TOPPLANT_ONLY_UNDER_PLANT
	}
}
