using System;

namespace Sexy
{
	public enum UI_ORIENTATION
	{
		UI_ORIENTATION_UNKNOWN,
		UI_ORIENTATION_PORTRAIT,
		UI_ORIENTATION_PORTRAIT_UPSIDE_DOWN,
		UI_ORIENTATION_LANDSCAPE_LEFT,
		UI_ORIENTATION_LANDSCAPE_RIGHT,
		UI_ORIENTATION_FACE_UP,
		UI_ORIENTATION_FACE_DOWN
	}
}
