using System;

namespace Sexy.TodLib
{
	public enum DrawStringJustification
	{
		DS_ALIGN_LEFT,
		DS_ALIGN_RIGHT,
		DS_ALIGN_CENTER,
		DS_ALIGN_LEFT_VERTICAL_MIDDLE,
		DS_ALIGN_RIGHT_VERTICAL_MIDDLE,
		DS_ALIGN_CENTER_VERTICAL_MIDDLE
	}
}
