using System;

namespace Sexy.TodLib
{
	public enum TodCurves
	{
		CURVE_CONSTANT,
		CURVE_LINEAR,
		CURVE_EASE_IN,
		CURVE_EASE_OUT,
		CURVE_EASE_IN_OUT,
		CURVE_EASE_IN_OUT_WEAK,
		CURVE_FAST_IN_OUT,
		CURVE_FAST_IN_OUT_WEAK,
		CURVE_WEAK_FAST_IN_OUT,
		CURVE_BOUNCE,
		CURVE_BOUNCE_FAST_MIDDLE,
		CURVE_BOUNCE_SLOW_MIDDLE,
		CURVE_SIN_WAVE,
		CURVE_EASE_SIN_WAVE
	}
}
