using System;

namespace Lawn
{
	public enum MusicTune
	{
		MUSIC_TUNE_NONE = -1,
		MUSIC_TUNE_DAY_GRASSWALK = 1,
		MUSIC_TUNE_NIGHT_MOONGRAINS,
		MUSIC_TUNE_POOL_WATERYGRAVES,
		MUSIC_TUNE_FOG_RIGORMORMIST,
		MUSIC_TUNE_ROOF_GRAZETHEROOF,
		MUSIC_TUNE_CHOOSE_YOUR_SEEDS,
		MUSIC_TUNE_TITLE_CRAZY_DAVE_MAIN_THEME,
		MUSIC_TUNE_PUZZLE_CEREBRAWL,
		MUSIC_TUNE_MINIGAME_LOONBOON,
		MUSIC_TUNE_CONVEYER,
		MUSIC_TUNE_FINAL_BOSS_BRAINIAC_MANIAC,
		MUSIC_TUNE_ZEN_GARDEN,
		NUM_MUSIC_TUNES
	}
}
