using System;

namespace Lawn
{
	public enum MusicFile
	{
		MUSIC_FILE_NONE = -1,
		MUSIC_FILE_MAIN_MUSIC = 1,
		MUSIC_FILE_DRUMS,
		MUSIC_FILE_HIHATS,
		MUSIC_FILE_CREDITS_ZOMBIES_ON_YOUR_LAWN,
		NUM_MUSIC_FILES
	}
}
