using System;

namespace Lawn
{
	public enum LeaderBoardButtonValues
	{
		LEADERBOARD_BUTTON_BACK,
		LEADERBOARD_BUTTON_PILE,
		LEADERBOARD_BUTTON_LEAVE_PILE,
		LEADERBOARD_BUTTON_VASEBREAKER,
		LEADERBOARD_BUTTON_IZOMBIE,
		LEADERBOARD_BUTTON_KILLED
	}
}
