using System;

namespace Lawn
{
	public enum ZombiePileObjectType
	{
		OBJECT_BALLOON,
		OBJECT_YELLOW_CLOUD,
		OBJECT_AIRPLANE,
		OBJECT_MOON,
		OBJECT_SATELLITE,
		OBJECT_PEGGLE_URSAMAJOR,
		OBJECT_ASTRONAUT,
		OBJECT_BLACKHOLE,
		OBJECT_ARROW,
		OBJECT_GEM0,
		OBJECT_GEM1,
		OBJECT_GEM2,
		OBJECT_GEM3,
		OBJECT_GEM4,
		OBJECT_GEM5,
		OBJECT_GEM6
	}
}
